version: '3'

services:

  reader-service:
    build:
      context: ./reader-service
      dockerfile: ./reader-service.dockerfile
    restart: always
    ports:
      - "5000:8080"
    deploy:
      mode: replicated
      replicas: 1

  front:
    container_name: docker-react-c
    image: docker-react-1
    build:
      context: ./reader-front/
      args:
        - API_URL=http://localhost:5000/
    ports:
      - 8080:80

